<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[test A]]>
    </line>
    <line>
      <![CDATA[end test A]]>
    </line>
    <line>
      <![CDATA[test B]]>
    </line>
    <line>
      <![CDATA[end test B]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="390" started-at="2020-04-12T10:45:49Z" finished-at="2020-04-12T10:45:49Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="390" started-at="2020-04-12T10:45:49Z" finished-at="2020-04-12T10:45:49Z">
      <class name="Testng.SoftAssert1">
        <test-method status="FAIL" signature="testA()[pri:0, instance:Testng.SoftAssert1@4678c730]" name="testA" duration-ms="94" started-at="2020-04-12T10:45:49Z" finished-at="2020-04-12T10:45:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [xyz] but found [abc]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [xyz] but found [abc]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Testng.SoftAssert1.testA(SoftAssert1.java:15)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[test A]]>
            </line>
            <line>
              <![CDATA[end test A]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="testB()[pri:0, instance:Testng.SoftAssert1@4678c730]" name="testB" duration-ms="19" started-at="2020-04-12T10:45:49Z" finished-at="2020-04-12T10:45:49Z">
          <reporter-output>
            <line>
              <![CDATA[test B]]>
            </line>
            <line>
              <![CDATA[end test B]]>
            </line>
          </reporter-output>
        </test-method> <!-- testB -->
      </class> <!-- Testng.SoftAssert1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
